version: '3.1'

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - /data/db
    ports:
      - '27017:27017'

  restapi:
    container_name: restapi
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    links:
      - mongo


